### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/noobs-install#1]
Hi @LornaLynch 

Could I get another copy edit please.

Thanks

**Comment by lauraclay** [comment]
Hi Marc

I'm also copied in on new Github notifications and I spotted @LornaLynch hasn't replied to this- if this is urgent (and she doesn't mind!) I'll assign this issue to myself and do as much as I can over lunch. (I'm usually assigned to web/magazine copy but I have some spare time now...)

**Comment by LornaLynch** [comment]
Sorry, guys: I have had to wait until Ronan went for his nap. I can get on with the copy edit now, if @lauraclay hasn't already powered through ;)

**Comment by lauraclay** [comment]
I'm off to have lunch so go for it :)

**Comment by LornaLynch** [comment]
Cheers!

**Comment by MarcScott** [comment]
Cheers to both of you. Much appreciated

**Comment by LornaLynch** [comment]
I think I'm done :)
