### ISSUE TITLE
Minor typo in worksheet.md

### ISSUE THREAD

**Issue by andres-mancera** [raspberrypilearning/noobs-install#2]
Over in the ["Writing NOOBS to an SD Card: Which OS?"](https://github.com/raspberrypilearning/noobs-install/blob/master/worksheet.md#writing-noobs-to-an-sd-card-which-os) section of the worksheet.md file, I noticed a minor typo in the first sentence.  It currently says: "If the SD card you **wsh** to install Raspbian on [...]".  It should be: "If the SD card you **wish** to install Raspbian on [...]".

I would like to fix that.  Is this a welcome contribution right now?

**Comment by lauraclay** [comment]
Thank you for spotting this- I've fixed it for quickness, but if you spot any more mistakes in the learning resources, please make the changes in a pull request and they will be merged.

**Comment by andres-mancera** [comment]
If that is the case, I suggest you re-word the guidelines that are posted over at [CONTRIBUTING.md](https://github.com/raspberrypilearning/noobs-install/blob/master/CONTRIBUTING.md).  As per the information that is given there, we are _supposed_ to first open an issue and then go ahead with the pull request (just like in most open source projects).  

A bit disappointed that I spotted the bug, but was not given a chance to fix it. :disappointed:
