### ISSUE TITLE
Update page to reflect changes

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/noobs-install#27]
URL: /en/projects/noobs-install

Looks like this page is out of time. NOOBS has gone. 

Can we check where the ingredient is used and update if needed.

**Comment by libxx1** [comment]
@MarcScott per conv. I can't see where this is used by us but it is getting views, though potentially not from internal referral. Ta.

**Comment by MarcScott** [comment]
Ignoring for now, as not used internally. Will archive this project, once archive features are introduced.
